### ISSUE TITLE
Train marshals for the SR2024 game

### ISSUE THREAD

**Issue by WillB97** [srobo/test#116]
The marshals should have a chance to run through the process of running a competition match sequence.
The marshals need to know:
  * what the rules are
  * who the expert on them is
  * who the judge is
  * how to use the score entry forms
  * the circumstances under which they should turn a robot off

Required actions:
 - [ ] Plan training
 - [ ] Organise a time to run training
 - [ ] Run training

### Original

[comp/volunteers/marshals-training](https://github.com/srobo/recurring-tasks/blob/master/comp/volunteers/marshals-training.yaml)
```[tasklist]
### Dependencies
 - [ ] #111 <!-- Schedule volunteer roles -->
 - [ ] #114 <!-- Organise match ops for the SR2024 competition -->
 - [ ] #115 <!-- Prepare competition-mode USB keys -->
```
