### ISSUE TITLE
[Meta] Have the SR2024 competition

### ISSUE THREAD

**Issue by WillB97** [srobo/test#135]
We need to have the SR2024 competition event.

### Original

[comp/main](https://github.com/srobo/recurring-tasks/blob/master/comp/main.yaml)
```[tasklist]
### Dependencies
 - [ ] #73 <!-- [Meta] Tidy up after the competition -->
 - [ ] #79 <!-- [Meta] Have the SR2024 virtual competition -->
 - [ ] #82 <!-- Organise tech days for SR2024 -->
 - [ ] #83 <!-- Prepare music playlists for the competition -->
 - [ ] #85 <!-- Organise computer hardware for the competition -->
 - [ ] #86 <!-- Kit handback arrangement -->
 - [ ] #87 <!-- Assign mentors to teams -->
 - [ ] #88 <!-- Publicise the competition on our Social Media -->
 - [ ] #90 <!-- Organise hotels and travel for volunteers -->
 - [ ] #91 <!-- Arrange first aid presence at the competition -->
 - [ ] #92 <!-- Organise photos to be taken at the competition -->
 - [ ] #93 <!-- Organise network access for the SR2024 competition -->
 - [ ] #94 <!-- Organise display screens for the SR2024 competition -->
 - [ ] #96 <!-- Organise equipment transport -->
 - [ ] #97 <!-- Prepare game equipment for the arena -->
 - [ ] #99 <!-- Plan competition teardown -->
 - [ ] #100 <!-- Prepare signage for the SR2024 Competition -->
 - [ ] #101 <!-- Organise battery management for the SR2024 competition -->
 - [ ] #102 <!-- Plan the welcome talk for competitors and guests -->
 - [ ] #104 <!-- Inform teams of details of the competition -->
 - [ ] #105 <!-- Schedule the matches for the SR2024 competition -->
 - [ ] #108 <!-- Organise the prize ceremony for the SR2024 competition -->
 - [ ] #109 <!-- Organise swag for the SR2024 competition -->
 - [ ] #110 <!-- Invite key people to the competition -->
 - [ ] #112 <!-- Inform volunteers for the SR2024 competition -->
 - [ ] #113 <!-- Brief volunteers at the SR2024 competition -->
 - [ ] #116 <!-- Train marshals for the SR2024 game -->
 - [ ] #120 <!-- Switch the website (proxy) to Competition Live mode for the SR2024 competition -->
 - [ ] #124 <!-- Print all the things for SR2024 -->
 - [ ] #125 <!-- Order volunteer shirts for the competition -->
 - [ ] #126 <!-- Plan volunteer meal for Saturday evening -->
 - [ ] #127 <!-- Plan lunch & refreshments for volunteers -->
 - [ ] #128 <!-- Appoint safeguarding officers for the SR2024 competition -->
 - [ ] #129 <!-- Safety check the SR2024 robots -->
 - [ ] #130 <!-- Determine and publish rules for the pits -->
 - [ ] #131 <!-- Announce the competition -->
 - [ ] #132 <!-- Plan who will be using the radios at the competition -->
 - [ ] #133 <!-- Organise how arena testing slots will be booked -->
 - [ ] #134 <!-- Setup machine to run score entry -->
```
