### ISSUE TITLE
[Meta] SR2024 Kickstart Event

### ISSUE THREAD

**Issue by WillB97** [srobo/test#54]
This is a barrier ticket for the SR2024 Kickstart event.
Tasks for the Kickstart event should be added as dependencies of this ticket.

### Original

[kickstart/event](https://github.com/srobo/recurring-tasks/blob/master/kickstart/event.yaml)
```[tasklist]
### Dependencies
- [ ] #41 <!--  -->
- [ ] #42 <!--  -->
- [ ] #44 <!--  -->
- [ ] #45 <!--  -->
- [ ] #46 <!-- Prepare a kickstart presentation -->
- [ ] #47 <!-- Update the simulator for the SR2024 game -->
- [ ] #48 <!-- Update and publish risk assessments for the Kickstart -->
- [ ] #49 <!-- Appoint safeguarding officers for SR2024 Kickstart -->
- [ ] #50 <!-- Create a budget for the SR2024 Competition Programme -->
- [ ] #51 <!-- Signup volunteers for the SR2024 Competition year -->
- [ ] #52 <!-- Work through open issues against the simulator -->
- [ ] #53 <!-- Prepare a livestream for the SR2024 Kickstart -->
```
