### ISSUE TITLE
[Meta] Have the SR2024 Kickstart

### ISSUE THREAD

**Issue by WillB97** [srobo/test#58]
We need to have the SR2024 Kickstarts.

### Original

[kickstart/main](https://github.com/srobo/recurring-tasks/blob/master/kickstart/main.yaml)
```[tasklist]
### Dependencies
 - [ ] #54 <!-- [Meta] SR2024 Kickstart Event -->
 - [ ] #55 <!-- Publish the rules for the SR2024 game -->
 - [ ] #56 <!-- Trim the live stream VOD (Video on Demand) -->
 - [ ] #57 <!-- Publish an article following the SR2024 Kickstart -->
```
