### ISSUE TITLE
[Meta] Tidy up after the competition

### ISSUE THREAD

**Issue by WillB97** [srobo/test#73]
Root ticket for all cleanup related items

### Original

[comp/cleanup](https://github.com/srobo/recurring-tasks/blob/master/comp/cleanup.yaml)
```[tasklist]
### Dependencies
 - [ ] #64 <!-- Trim the live stream VOD (Video on Demand) for the SR2024 competition -->
 - [ ] #68 <!-- Publish an article following the SR2024 Competition -->
 - [ ] #71 <!-- Create post competiton reports -->
 - [ ] #72 <!-- Send a wrap-up email to teams -->
```
