### ISSUE TITLE
[Meta] Have the SR2024 virtual competition

### ISSUE THREAD

**Issue by WillB97** [srobo/test#79]
Root ticket for the virtual competition.

### Original

[comp/virtual-comp/main](https://github.com/srobo/recurring-tasks/blob/master/comp/virtual-comp/main.yaml)
```[tasklist]
### Dependencies
 - [ ] #74 <!-- Appoint safeguarding officers for the virtual competition -->
 - [ ] #75 <!-- Plan simulating the SR2024 virtual competition -->
 - [ ] #76 <!-- Setup code submitter for SR2024 virtual competition -->
 - [ ] #78 <!-- Trim the live stream VOD (Video on Demand) for the virtual competition -->
```
